[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "biblioteca"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "Django==5.2.14",
    "pyodbc",
    "python-dotenv==1.1.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-django",
    "behave==1.3.3"
]