# Generated by Django 5.2.14 on 2026-05-20 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=50)),
                ('data_pub', models.DateField()),
                ('original', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('S', 'Sugerido'), ('D', 'Disponível'), ('E', 'Emprestado'), ('R', 'Reservado'), ('O', 'Retirado')], default='D', max_length=1)),
                ('data_add', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['titulo'], name='livros_livr_titulo_f6efa9_idx'), models.Index(fields=['tipo'], name='livros_livr_tipo_77f1a4_idx'), models.Index(fields=['tema'], name='livros_livr_tema_228879_idx')],
            },
        ),
    ]
