# Generated by Django 5.2.14 on 2026-05-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('nipc', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nipc'],
                'indexes': [models.Index(fields=['nipc'], name='livros_edit_nipc_594407_idx'), models.Index(fields=['nome'], name='livros_edit_nome_563776_idx')],
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.editora'),
        ),
    ]
