# Generated by Django 5.2.14 on 2026-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_editora_alter_livro_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('sigla', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='livros_tema_nome_d376e1_idx'), models.Index(fields=['sigla'], name='livros_tema_sigla_2902d4_idx')],
            },
        ),
    ]
