# Generated by Django 5.2.14 on 2026-06-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_tema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livro',
            new_name='livros_livr_tema_id_504149_idx',
            old_name='livros_livr_tema_228879_idx',
        ),
        migrations.AlterField(
            model_name='livro',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.tema'),
        ),
    ]
