# Generated by Django 5.2.14 on 2026-06-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_rename_livros_livr_tema_228879_idx_livros_livr_tema_id_504149_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(to='livros.autor'),
        ),
        migrations.CreateModel(
            name='ZonasGeograficas',
            fields=[
                ('sigla', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['sigla'], name='livros_zona_sigla_036719_idx'), models.Index(fields=['nome'], name='livros_zona_nome_42064b_idx')],
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.zonasgeograficas'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['nome'], name='livros_auto_nome_1bd81a_idx'),
        ),
    ]
