# Generated by Django 6.0.6 on 2026-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_autor_alter_livro_data_pub_livro_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('altura', models.FloatField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('pais_origem', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveIndex(
            model_name='autor',
            name='livros_auto_nome_1bd81a_idx',
        ),
        migrations.RemoveIndex(
            model_name='editora',
            name='livros_edit_nipc_594407_idx',
        ),
        migrations.RemoveIndex(
            model_name='editora',
            name='livros_edit_nome_563776_idx',
        ),
        migrations.RemoveIndex(
            model_name='livro',
            name='livros_livr_titulo_f6efa9_idx',
        ),
        migrations.RemoveIndex(
            model_name='livro',
            name='livros_livr_tipo_77f1a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='livro',
            name='livros_livr_tema_id_504149_idx',
        ),
        migrations.RemoveIndex(
            model_name='tema',
            name='livros_tema_nome_d376e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='tema',
            name='livros_tema_sigla_2902d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='zonasgeograficas',
            name='livros_zona_sigla_036719_idx',
        ),
        migrations.RemoveIndex(
            model_name='zonasgeograficas',
            name='livros_zona_nome_42064b_idx',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='tema',
        ),
        migrations.DeleteModel(
            name='ZonasGeograficas',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
